[project]
name = "hypercube"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "cython>=3.0.12",
    "jax>=0.6.2",
    "matplotlib>=3.10.3",
]
